// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package role

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func RoleResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"description": schema.StringAttribute{
				Optional:            true,
				Description:         "Description",
				MarkdownDescription: "Description",
			},
			"id": schema.Int64Attribute{
				Computed:            true,
				Description:         "",
				MarkdownDescription: "",
			},
			"multitenant": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Multitenant roles are copied to all tenant accounts and kept in sync until a sub-tenant user modifies their copy of the role. *Only available to master tenant*",
				MarkdownDescription: "Multitenant roles are copied to all tenant accounts and kept in sync until a sub-tenant user modifies their copy of the role. *Only available to master tenant*",
				Default:             booldefault.StaticBool(false),
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "a unique name of the role",
				MarkdownDescription: "a unique name of the role",
			},
		},
	}
}

type RoleModel struct {
	Description types.String `tfsdk:"description"`
	Id          types.Int64  `tfsdk:"id"`
	Multitenant types.Bool   `tfsdk:"multitenant"`
	Name        types.String `tfsdk:"name"`
}
