// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package group

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func GroupDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"code": schema.StringAttribute{
				Computed:            true,
				Description:         "Optional code for use with policies",
				MarkdownDescription: "Optional code for use with policies",
			},
			"id": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Morpheus ID of the Object being referenced",
				MarkdownDescription: "Morpheus ID of the Object being referenced",
				Validators: []validator.Int64{
					int64validator.ConflictsWith(path.Expressions{
						path.MatchRoot("name"),
					}...),
				},
			},
			"location": schema.StringAttribute{
				Computed:            true,
				Description:         "Optional location argument for your group",
				MarkdownDescription: "Optional location argument for your group",
			},
			"name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The name of the Morpheus group",
				MarkdownDescription: "The name of the Morpheus group",
				Validators: []validator.String{
					stringvalidator.ConflictsWith(path.Expressions{
						path.MatchRoot("id"),
					}...),
				},
			},
		},
	}
}

type GroupModel struct {
	Code     types.String `tfsdk:"code"`
	Id       types.Int64  `tfsdk:"id"`
	Location types.String `tfsdk:"location"`
	Name     types.String `tfsdk:"name"`
}
